wangle: match folly default compiler level
Summary:
The first problem I want to solve is this linker failure
when building the wangle tests:

```
CMakeFiles/SSLContextManagerTest.dir/ssl/test/SSLContextManagerTest.cpp.o: In function `wangle::SSLContextManagerTest_DISABLED_TestSessionContextIfS upplied_Test::TestBody()':
include/folly/String-inl.h:465: undefined reference to `folly::ssl::SSLServerOptions::kCipherList'
```

AFAICT this is due to differences in implicit inline and external linkage for
static constexpr variables.  I believe that folly's default newer compiler
standard is generating these as mostly inline symbols; here's what I see in the
object file:

```
$ nm -s folly/io/async/SSLOptions.cpp.o | grep kCipher
0000000000000000 u _ZN5folly3ssl16SSLCommonOptions11kCipherListE
```

Making the wangle compiler defaults match the folly defaults means that the
code will be generated consistently between the two, effectively dancing around
this issue.

Reviewed By: yfeldblum

Differential Revision: D14700298

fbshipit-source-id: 4138b9bfb5472b4ef0911d6029952edd13869c47