Improve error handling in FilePollerTest
Summary:
On Windows, FilePollerTest.TestCreateFile is failing:

```
[ RUN      ] FilePollerTest.TestCreateFile
c:\open\fbsource\fbcode\wangle\util\test\filepollertest.cpp(143): error: Value of: baton.try_wait_for(seconds(5))
  Actual: false
Expected: true
[  FAILED  ] FilePollerTest.TestCreateFile (5007 ms)
```

I debugged the failure and discovered that `remove` is failing silently.

Make `remove` failures easier to debug by failing the test if `remove` fails:

```
[ RUN      ] FilePollerTest.TestCreateFile
c:\open\fbsource\fbcode\wangle\util\test\filepollertest.cpp(138): error: Expected equality of these values:
  remove(tmpFile.c_str())
    Which is: -1
  0
Permission denied
[  FAILED  ] FilePollerTest.TestCreateFile (7 ms)
```

This change exposes a bug: TestDeleteFile isn't testing what it's supposed to test:

```
[ RUN      ] FilePollerTest.TestDeleteFile
c:\open\fbsource\fbcode\wangle\util\test\filepollertest.cpp(158): error: Expected equality of these values:
  remove(tmpFile.c_str())
    Which is: -1
  0
Permission denied
[  FAILED  ] FilePollerTest.TestDeleteFile (4 ms)
```

(D13984789 makes `remove` not fail in FilePollerTest.TestCreateFile on Windows.)

Reviewed By: yfeldblum

Differential Revision: D13984785

fbshipit-source-id: 9af46cf387a39277dfbadc60f5b218a0589fb607