wangle: unbreak FilePersistenceLayer.cpp build on win32
Summary:
D14714163 added this file to the cmake build but overlooked the build
failure that showed up on the diff during code review:

```
wangle\client\persistence\filepersistencelayer.cpp(39): error C2065: 'S_IRUSR': undeclared identifier
wangle\client\persistence\filepersistencelayer.cpp(39): error C2065: 'S_IWUSR': undeclared identifier
```

rather than using the posix symbols, just use the numeric value, which is consistent with
how `folly::writeFile` defaults the mode parameter.

Reviewed By: yfeldblum

Differential Revision: D14721830

fbshipit-source-id: 3600cbd9280f715a85cb6a576aff83efcb241b0d