Fix ASAN-reported heap-use-after-free in FilePoller
Summary:
[Wangle] Fix ASAN-reported `heap-use-after-free` in `FilePoller`.

The problem is that if the polling function is currently running while `FilePoller` dtor is called, then the polling function will continue to run to completion, which may include referencing into the destructed `FilePoller`. We must ensure that the polling function is not running between cancelling it and destructing the `FilePoller` instance.

Discovered while running some unrelated test case from some unrelated internal project with ASAN. A cleaned-up version of the ASAN report follows:
```lang=none
ERROR: AddressSanitizer: heap-use-after-free
READ of size 8 at 0x602000008370 thread T2 (file-poller)
     #4 wangle/util/FilePoller.cpp:90            wangle::FilePoller::checkFiles()
     #5 wangle/util/FilePoller.cpp:69            wangle::FilePoller::init(std::chrono::duration<...>)::$_2::operator()() const
     #6 folly/Function.h:298                     void folly::detail::function::FunctionTraits<...>::callSmall<...>(folly::detail::function::Data&)
     #7 folly/Function.h:314                     folly::detail::function::FunctionTraits<...>::operator()()
     #8 folly/experimental/FunctionScheduler.cpp:432 folly::FunctionScheduler::runOneFunction(std::unique_lock<...>&, std::chrono::time_point<...>)
     #9 folly/experimental/FunctionScheduler.cpp:384 folly::FunctionScheduler::run()
    #10 folly/experimental/FunctionScheduler.cpp:334 folly::FunctionScheduler::start()::$_2::operator()() const

0x602000008370 is located 0 bytes inside of 16-byte region [0x602000008370,0x602000008380)
freed by thread T0 here:
     #0 ??:?                                     operator delete(void*)
     #5 wangle/util/FilePoller.h:97              wangle::FilePoller::FileData::~FileData()
     #6 folly/Traits.h:475                       std::pair<...>::~pair()
    #14 wangle/util/FilePoller.cpp:59            wangle::FilePoller::~FilePoller()
    #15 wangle/util/FilePoller.cpp:59            wangle::FilePoller::~FilePoller()
    #18 thrift/lib/cpp2/security/SecurityKillSwitchPoller.cpp:64 apache::thrift::SecurityKillSwitchPoller::~SecurityKillSwitchPoller()
    #19 thrift/lib/cpp2/server/ThriftServer.cpp:150 apache::thrift::ThriftServer::~ThriftServer()
    #26 folly/Traits.h:498                       std::shared_ptr<...>::~shared_ptr()
    #27 thrift/lib/cpp2/util/ScopedServerInterfaceThread.h:36 apache::thrift::ScopedServerInterfaceThread::~ScopedServerInterfaceThread()

previously allocated by thread T0 here:
     #0 ??:?                                     operator new(unsigned long)
     #4 wangle/util/FilePoller.h:99              wangle::FilePoller::FileData::FileData(std::function<...>, std::function<...>, std::function<...>)
     #5 wangle/util/FilePoller.cpp:117           wangle::FilePoller::addFileToTrack(std::__cxx11::basic_string<...> const&, std::function<...>, std::function<...>, std::function<...>)
     #6 thrift/lib/cpp2/security/SecurityKillSwitchPoller.cpp:50 apache::thrift::SecurityKillSwitchPoller::SecurityKillSwitchPoller(bool)
     #7 thrift/lib/cpp2/security/SecurityKillSwitchPoller.cpp:42 apache::thrift::SecurityKillSwitchPoller::SecurityKillSwitchPoller()
     #8 thrift/lib/cpp2/server/ThriftServer.cpp:95 apache::thrift::ThriftServer::ThriftServer(std::__cxx11::basic_string<...> const&, bool)
     #9 thrift/lib/cpp2/server/ThriftServer.cpp:93 apache::thrift::ThriftServer::ThriftServer()
    #18 thrift/lib/cpp2/util/ScopedServerInterfaceThread.cpp:35 apache::thrift::ScopedServerInterfaceThread::ScopedServerInterfaceThread(std::shared_ptr<...>, folly::SocketAddress const&, folly::Function<...>)
    #19 thrift/lib/cpp2/util/ScopedServerInterfaceThread.cpp:52 apache::thrift::ScopedServerInterfaceThread::ScopedServerInterfaceThread(std::shared_ptr<...>, std::__cxx11::basic_string<...> const&, unsigned short, folly::Function<...>)

Thread T2 (file-poller) created by T0 here:
     #0 ??:?                                     pthread_create
     #4 folly/experimental/FunctionScheduler.cpp:334 folly::FunctionScheduler::start()
     #5 wangle/util/FilePoller.cpp:28            wangle::(anonymous namespace)::PollerContext::PollerContext()
     #6 wangle/util/FilePoller.cpp:45            wangle::(anonymous namespace)::$_0::operator()() const
     #9 folly/Singleton-inl.h:258                folly::detail::SingletonHolder<...>::createInstance()
    #10 folly/Singleton-inl.h:123                folly::detail::SingletonHolder<...>::try_get()
    #11 folly/Singleton.h:564                    folly::Singleton<...>::try_get()
    #12 wangle/util/FilePoller.cpp:62            wangle::FilePoller::init(std::chrono::duration<...>)
    #13 wangle/util/FilePoller.cpp:56            wangle::FilePoller::FilePoller(std::chrono::duration<...>)
    #15 thrift/lib/cpp2/security/SecurityKillSwitchPoller.cpp:45 apache::thrift::SecurityKillSwitchPoller::SecurityKillSwitchPoller(bool)
    #16 thrift/lib/cpp2/security/SecurityKillSwitchPoller.cpp:42 apache::thrift::SecurityKillSwitchPoller::SecurityKillSwitchPoller()
    #17 thrift/lib/cpp2/server/ThriftServer.cpp:95 apache::thrift::ThriftServer::ThriftServer(std::__cxx11::basic_string<...> const&, bool)
    #18 thrift/lib/cpp2/server/ThriftServer.cpp:93 apache::thrift::ThriftServer::ThriftServer()
    #27 thrift/lib/cpp2/util/ScopedServerInterfaceThread.cpp:35 apache::thrift::ScopedServerInterfaceThread::ScopedServerInterfaceThread(std::shared_ptr<...>, folly::SocketAddress const&, folly::Function<...>)
    #28 thrift/lib/cpp2/util/ScopedServerInterfaceThread.cpp:52 apache::thrift::ScopedServerInterfaceThread::ScopedServerInterfaceThread(std::shared_ptr<...>, std::__cxx11::basic_string<...> const&, unsigned short, folly::Function<...>)
```

Reviewed By: siyengar

Differential Revision: D5059743

fbshipit-source-id: b8de4c3c86a36c747efe31875ed712a4b77ce7af