wangle: stop using GMOCK_METHOD1_ and company; use MOCK_METHOD instead.
Summary:
The GMOCK_METHOD1_-style macros no longer compile with clang-12/C++20.
From here: https://github.com/google/googletest/releases/tag/release-1.10.0
You see that the old idiom,
  MOCK_METHOD1(Bar, double(std::string s));
can be rewritten like this:
  MOCK_METHOD(double, Bar, (std::string s), (override));

I.e., Change this
  GMOCK_METHOD1_(, noexcept, , m, void(AsyncTransport*));
to this:
  MOCK_METHOD(void, m, (AsyncTransport*), (noexcept));

Most changes were induced by running this filter on matching lines:
  perl -pe 's{GMOCK_METHOD\d+_\(, ([^,]*), , ([^,]+), (\S+)\((.*?)\)\);}{MOCK_METHOD($3, $2, ($4), ($1));}'

This avoids the following errors:

  wangle/ssl/test/MockSSLStats.h:26:26: error: unknown type name 'recordTLSTicketRotation'
  wangle/ssl/test/MockSSLStats.h:26:3: error: C++ requires a type specifier for all declarations
  wangle/ssl/test/MockSSLStats.h:26:51: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:26:51: error: expected parameter declarator
  wangle/ssl/test/MockSSLStats.h:26:52: error: C++ requires a type specifier for all declarations
  wangle/ssl/test/MockSSLStats.h:26:52: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:32:3: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:32:3: error: expected parameter declarator
  wangle/ssl/test/MockSSLStats.h:32:3: error: pasting formed ')_', an invalid preprocessing token
  wangle/ssl/test/MockSSLStats.h:32:3: error: static_assert failed "void(bool valid) should be enclosed in parentheses."
  wangle/ssl/test/MockSSLStats.h:32:3: error: unknown type name 'GMOCK_PP_INTERNAL_FOR_EACH_IMPL_GMOCK_PP_NARG0'
  wangle/ssl/test/MockSSLStats.h:32:3: error: use of undeclared identifier 'GMOCK_PP_INTERNAL_FOR_EACH_IMPL_GMOCK_PP_NARG0'
  wangle/ssl/test/MockSSLStats.h:32:3: error: use of undeclared identifier 'GMOCK_PP_NARG0'
  wangle/ssl/test/MockSSLStats.h:32:46: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:32:46: error: expected ';' at end of declaration list
  wangle/ssl/test/MockSSLStats.h:44:3: error: C++ requires a type specifier for all declarations
  wangle/ssl/test/MockSSLStats.h:45:7: error: unknown type name 'recordSSLUpstreamConnection'
  wangle/ssl/test/MockSSLStats.h:46:7: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:46:7: error: expected parameter declarator
  wangle/ssl/test/MockSSLStats.h:50:3: error: C++ requires a type specifier for all declarations
  wangle/ssl/test/MockSSLStats.h:51:7: error: unknown type name 'recordSSLUpstreamConnection'
  wangle/ssl/test/MockSSLStats.h:52:7: error: expected ')'
  wangle/ssl/test/MockSSLStats.h:52:7: error: expected parameter declarator

  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:109:5: error: no member named 'gmock_setPersistedVersion' in 'MockPersistenceLayer'
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:318:3: error: no member named 'gmock_setPersistedVersion' in 'MockPersistenceLayer'
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:371:3: error: no member named 'gmock_setPersistedVersion' in 'MockPersistenceLayer'
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:97:18: error: expected parameter declarator
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:97:20: error: expected ')'
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:97:20: error: expected parameter declarator
  wangle/client/persistence/test/LRUPersistentCacheTest.cpp:97:3: error: C++ requires a type specifier for all declarations

  wangle/acceptor/test/AcceptorTest.cpp:168:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:168:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:168:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:168:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:169:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:169:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:169:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:169:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:170:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:170:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:170:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:170:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:171:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:171:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:171:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:171:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:172:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:172:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:172:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:172:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:177:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:177:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:177:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:177:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:178:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:178:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:178:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:178:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:179:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:179:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:179:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:179:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:180:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:180:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:180:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:180:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:181:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:181:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:181:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:181:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:182:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:182:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:182:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:182:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:183:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:183:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:183:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:183:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:184:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:184:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:184:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:184:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:185:18: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:185:20: error: expected ')'
  wangle/acceptor/test/AcceptorTest.cpp:185:20: error: expected parameter declarator
  wangle/acceptor/test/AcceptorTest.cpp:185:3: error: C++ requires a type specifier for all declarations
  wangle/acceptor/test/AcceptorTest.cpp:227:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:234:5: error: no member named 'gmock_accept' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:235:5: error: no member named 'gmock_ready' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:246:5: error: no member named 'gmock_accept' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:247:5: error: no member named 'gmock_ready' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:255:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:275:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:279:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:303:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:313:3: error: no member named 'gmock_acceptorDestroy' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:321:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:326:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:330:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:334:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:347:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:352:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:356:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:360:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:373:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:378:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:388:3: error: no member named 'gmock_acceptorDestroy' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:389:3: error: no member named 'gmock_acceptorDestroy' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:398:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:402:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:414:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:422:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:454:3: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:468:3: error: no member named 'gmock_accept' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:472:9: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:479:5: error: no member named 'gmock_fdDetach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:484:5: error: no member named 'gmock_move' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:493:11: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:495:32: error: no viable conversion from '(lambda at wangle/acceptor/test/AcceptorTest.cpp:495:32)' to '(lambda at wangle/acceptor/test/AcceptorTest.cpp:495:32)'
  wangle/acceptor/test/AcceptorTest.cpp:496:17: error: variable 'gtest_ar' cannot be implicitly captured in a lambda with no capture-default specified
  wangle/acceptor/test/AcceptorTest.cpp:503:11: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:526:5: error: no member named 'gmock_fdDetach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:531:5: error: no member named 'gmock_move' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:543:11: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:545:32: error: no viable conversion from '(lambda at wangle/acceptor/test/AcceptorTest.cpp:545:32)' to '(lambda at wangle/acceptor/test/AcceptorTest.cpp:545:32)'
  wangle/acceptor/test/AcceptorTest.cpp:546:17: error: variable 'gtest_ar' cannot be implicitly captured in a lambda with no capture-default specified
  wangle/acceptor/test/AcceptorTest.cpp:553:11: error: no member named 'gmock_observerAttach' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:565:3: error: no member named 'gmock_ready' in 'testing::StrictMock<MockAcceptObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:574:3: error: no member named 'gmock_close' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:579:3: error: no member named 'gmock_destroy' in 'testing::StrictMock<MockAsyncSocketLifecycleObserver>'
  wangle/acceptor/test/AcceptorTest.cpp:596:3: error: no member named 'gmock_observerDetach' in 'testing::StrictMock<MockAcceptObserver>'

Differential Revision: D34164875

fbshipit-source-id: 6f20553d590f774aafc77a850509e315a38c9b3d